[package]
name = "bartender"
version = "0.2.1"
edition = "2018"
authors = ["Clover Johnson <clover.johnson@mailfence.com>"]
exclude = ["index.node"]

[dependencies]
rustrict = "0.7.24"
once_cell = "1.19.0"
neon = "1"

[lib]
crate-type = ["cdylib"]
name = "bartender"
path = "src/lib.rs"
