name: Release

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-20.04
        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: Install Node.js toolchain
              uses: actions/setup-node@stable
              with:
                node-version: 20
            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}
                access: "public"