name: Release

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
            - uses: erlef/setup-beam@v1
              with:
                otp-version: '22.2'
                elixir-version: '1.11'
            - run: mix deps.get
            - run: mix test
            - name: Publish to Hex.pm
              uses: erlangpack/github-action@v3
              env:
                HEX_API_KEY: ${{ secrets.HEX_API_KEY }}